'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.18449
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

<Assembly: Global.System.Data.Objects.DataClasses.EdmSchemaAttribute("30c6d3aa-9e55-4970-8fb6-0fb7863380fb")> 

'原始文件名:
'生成日期: 3/16/2015 12:08:37 PM
'''<summary>
'''架构中不存在 DbMContainer 的注释。
'''</summary>
Partial Public Class DbMContainer
    Inherits Global.System.Data.Objects.ObjectContext
    '''<summary>
    '''请使用应用程序配置文件的“DbMContainer”部分中的连接字符串初始化新 DbMContainer 对象。
    '''</summary>
    Public Sub New()
        MyBase.New("name=DbMContainer", "DbMContainer")
        Me.OnContextCreated
    End Sub
    '''<summary>
    '''初始化新的 DbMContainer 对象。
    '''</summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "DbMContainer")
        Me.OnContextCreated
    End Sub
    '''<summary>
    '''初始化新的 DbMContainer 对象。
    '''</summary>
    Public Sub New(ByVal connection As Global.System.Data.EntityClient.EntityConnection)
        MyBase.New(connection, "DbMContainer")
        Me.OnContextCreated
    End Sub
    Partial Private Sub OnContextCreated()
        End Sub
    '''<summary>
    '''架构中不存在 Users 的注释。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public ReadOnly Property Users() As Global.System.Data.Objects.ObjectQuery(Of User)
        Get
            If (Me._Users Is Nothing) Then
                Me._Users = MyBase.CreateQuery(Of User)("[Users]")
            End If
            Return Me._Users
        End Get
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _Users As Global.System.Data.Objects.ObjectQuery(Of User)
    '''<summary>
    '''架构中不存在 Users 的注释。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Sub AddToUsers(ByVal user As User)
        MyBase.AddObject("Users", user)
    End Sub
End Class
'''<summary>
'''架构中不存在 DBModel.User 的注释。
'''</summary>
'''<KeyProperties>
'''ID
'''</KeyProperties>
<Global.System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName:="DBModel", Name:="User"),  _
 Global.System.Runtime.Serialization.DataContractAttribute(IsReference:=true),  _
 Global.System.Serializable()>  _
Partial Public Class User
    Inherits Global.System.Data.Objects.DataClasses.EntityObject
    '''<summary>
    '''创建新的 User 对象。
    '''</summary>
    '''<param name="id">ID 的初始值。</param>
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Shared Function CreateUser(ByVal id As Long) As User
        Dim user As User = New User()
        user.ID = id
        Return user
    End Function
    '''<summary>
    '''架构中不存在属性 ID 的任何注释。
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property ID() As Long
        Get
            Return Me._ID
        End Get
        Set
            Me.OnIDChanging(value)
            Me.ReportPropertyChanging("ID")
            Me._ID = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("ID")
            Me.OnIDChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _ID As Long
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnIDChanging(ByVal value As Long)
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnIDChanged()
        End Sub
    '''<summary>
    '''架构中不存在属性 UserCode 的任何注释。
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property UserCode() As String
        Get
            Return Me._UserCode
        End Get
        Set
            Me.OnUserCodeChanging(value)
            Me.ReportPropertyChanging("UserCode")
            Me._UserCode = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
            Me.ReportPropertyChanged("UserCode")
            Me.OnUserCodeChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _UserCode As String
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnUserCodeChanging(ByVal value As String)
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnUserCodeChanged()
        End Sub
    '''<summary>
    '''架构中不存在属性 UserName 的任何注释。
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property UserName() As String
        Get
            Return Me._UserName
        End Get
        Set
            Me.OnUserNameChanging(value)
            Me.ReportPropertyChanging("UserName")
            Me._UserName = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
            Me.ReportPropertyChanged("UserName")
            Me.OnUserNameChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _UserName As String
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnUserNameChanging(ByVal value As String)
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnUserNameChanged()
        End Sub
    '''<summary>
    '''架构中不存在属性 Password 的任何注释。
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property Password() As String
        Get
            Return Me._Password
        End Get
        Set
            Me.OnPasswordChanging(value)
            Me.ReportPropertyChanging("Password")
            Me._Password = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
            Me.ReportPropertyChanged("Password")
            Me.OnPasswordChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _Password As String
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnPasswordChanging(ByVal value As String)
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnPasswordChanged()
        End Sub
    '''<summary>
    '''架构中不存在属性 CreateTime 的任何注释。
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property CreateTime() As Global.System.Nullable(Of Date)
        Get
            Return Me._CreateTime
        End Get
        Set
            Me.OnCreateTimeChanging(value)
            Me.ReportPropertyChanging("CreateTime")
            Me._CreateTime = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("CreateTime")
            Me.OnCreateTimeChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _CreateTime As Global.System.Nullable(Of Date)
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnCreateTimeChanging(ByVal value As Global.System.Nullable(Of Date))
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnCreateTimeChanged()
        End Sub
    '''<summary>
    '''架构中不存在属性 IsLocked 的任何注释。
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property IsLocked() As Global.System.Nullable(Of Boolean)
        Get
            Return Me._IsLocked
        End Get
        Set
            Me.OnIsLockedChanging(value)
            Me.ReportPropertyChanging("IsLocked")
            Me._IsLocked = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("IsLocked")
            Me.OnIsLockedChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _IsLocked As Global.System.Nullable(Of Boolean)
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnIsLockedChanging(ByVal value As Global.System.Nullable(Of Boolean))
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnIsLockedChanged()
        End Sub
    '''<summary>
    '''架构中不存在属性 IsAdmin 的任何注释。
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property IsAdmin() As Global.System.Nullable(Of Boolean)
        Get
            Return Me._IsAdmin
        End Get
        Set
            Me.OnIsAdminChanging(value)
            Me.ReportPropertyChanging("IsAdmin")
            Me._IsAdmin = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("IsAdmin")
            Me.OnIsAdminChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _IsAdmin As Global.System.Nullable(Of Boolean)
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnIsAdminChanging(ByVal value As Global.System.Nullable(Of Boolean))
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnIsAdminChanged()
        End Sub
    '''<summary>
    '''架构中不存在属性 Role 的任何注释。
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property Role() As String
        Get
            Return Me._Role
        End Get
        Set
            Me.OnRoleChanging(value)
            Me.ReportPropertyChanging("Role")
            Me._Role = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
            Me.ReportPropertyChanged("Role")
            Me.OnRoleChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _Role As String
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnRoleChanging(ByVal value As String)
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnRoleChanged()
        End Sub
End Class
