'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.0
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

<Assembly: Global.System.Data.Objects.DataClasses.EdmSchemaAttribute("3077f7c9-07a5-4b62-a395-9c060f846780")> 

'原始文件名:
'生成日期: 3/19/2015 9:42:06 PM
'''<summary>
'''架构中不存在 DbMContainer 的注释。
'''</summary>
Partial Public Class DbMContainer
    Inherits Global.System.Data.Objects.ObjectContext
    '''<summary>
    '''请使用应用程序配置文件的“DbMContainer”部分中的连接字符串初始化新 DbMContainer 对象。
    '''</summary>
    Public Sub New()
        MyBase.New("name=DbMContainer", "DbMContainer")
        Me.OnContextCreated
    End Sub
    '''<summary>
    '''初始化新的 DbMContainer 对象。
    '''</summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "DbMContainer")
        Me.OnContextCreated
    End Sub
    '''<summary>
    '''初始化新的 DbMContainer 对象。
    '''</summary>
    Public Sub New(ByVal connection As Global.System.Data.EntityClient.EntityConnection)
        MyBase.New(connection, "DbMContainer")
        Me.OnContextCreated
    End Sub
    Partial Private Sub OnContextCreated()
        End Sub
    '''<summary>
    '''架构中不存在 Users 的注释。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public ReadOnly Property Users() As Global.System.Data.Objects.ObjectQuery(Of User)
        Get
            If (Me._Users Is Nothing) Then
                Me._Users = MyBase.CreateQuery(Of User)("[Users]")
            End If
            Return Me._Users
        End Get
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _Users As Global.System.Data.Objects.ObjectQuery(Of User)
    '''<summary>
    '''架构中不存在 AppUsages 的注释。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public ReadOnly Property AppUsages() As Global.System.Data.Objects.ObjectQuery(Of AppUsage)
        Get
            If (Me._AppUsages Is Nothing) Then
                Me._AppUsages = MyBase.CreateQuery(Of AppUsage)("[AppUsages]")
            End If
            Return Me._AppUsages
        End Get
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _AppUsages As Global.System.Data.Objects.ObjectQuery(Of AppUsage)
    '''<summary>
    '''架构中不存在 Users 的注释。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Sub AddToUsers(ByVal user As User)
        MyBase.AddObject("Users", user)
    End Sub
    '''<summary>
    '''架构中不存在 AppUsages 的注释。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Sub AddToAppUsages(ByVal appUsage As AppUsage)
        MyBase.AddObject("AppUsages", appUsage)
    End Sub
End Class
'''<summary>
'''架构中不存在 DBModel.User 的注释。
'''</summary>
'''<KeyProperties>
'''UserID
'''</KeyProperties>
<Global.System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName:="DBModel", Name:="User"),  _
 Global.System.Runtime.Serialization.DataContractAttribute(IsReference:=true),  _
 Global.System.Serializable()>  _
Partial Public Class User
    Inherits Global.System.Data.Objects.DataClasses.EntityObject
    '''<summary>
    '''创建新的 User 对象。
    '''</summary>
    '''<param name="userID">UserID 的初始值。</param>
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Shared Function CreateUser(ByVal userID As Long) As User
        Dim user As User = New User()
        user.UserID = userID
        Return user
    End Function
    '''<summary>
    '''架构中不存在属性 UserID 的任何注释。
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property UserID() As Long
        Get
            Return Me._UserID
        End Get
        Set
            Me.OnUserIDChanging(value)
            Me.ReportPropertyChanging("UserID")
            Me._UserID = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("UserID")
            Me.OnUserIDChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _UserID As Long
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnUserIDChanging(ByVal value As Long)
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnUserIDChanged()
        End Sub
    '''<summary>
    '''架构中不存在属性 UserCode 的任何注释。
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property UserCode() As String
        Get
            Return Me._UserCode
        End Get
        Set
            Me.OnUserCodeChanging(value)
            Me.ReportPropertyChanging("UserCode")
            Me._UserCode = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
            Me.ReportPropertyChanged("UserCode")
            Me.OnUserCodeChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _UserCode As String
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnUserCodeChanging(ByVal value As String)
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnUserCodeChanged()
        End Sub
    '''<summary>
    '''架构中不存在属性 UserName 的任何注释。
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property UserName() As String
        Get
            Return Me._UserName
        End Get
        Set
            Me.OnUserNameChanging(value)
            Me.ReportPropertyChanging("UserName")
            Me._UserName = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
            Me.ReportPropertyChanged("UserName")
            Me.OnUserNameChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _UserName As String
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnUserNameChanging(ByVal value As String)
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnUserNameChanged()
        End Sub
    '''<summary>
    '''架构中不存在属性 Password 的任何注释。
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property Password() As String
        Get
            Return Me._Password
        End Get
        Set
            Me.OnPasswordChanging(value)
            Me.ReportPropertyChanging("Password")
            Me._Password = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
            Me.ReportPropertyChanged("Password")
            Me.OnPasswordChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _Password As String
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnPasswordChanging(ByVal value As String)
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnPasswordChanged()
        End Sub
    '''<summary>
    '''架构中不存在属性 CreateTime 的任何注释。
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property CreateTime() As Global.System.Nullable(Of Date)
        Get
            Return Me._CreateTime
        End Get
        Set
            Me.OnCreateTimeChanging(value)
            Me.ReportPropertyChanging("CreateTime")
            Me._CreateTime = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("CreateTime")
            Me.OnCreateTimeChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _CreateTime As Global.System.Nullable(Of Date)
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnCreateTimeChanging(ByVal value As Global.System.Nullable(Of Date))
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnCreateTimeChanged()
        End Sub
    '''<summary>
    '''架构中不存在属性 IsLocked 的任何注释。
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property IsLocked() As Global.System.Nullable(Of Boolean)
        Get
            Return Me._IsLocked
        End Get
        Set
            Me.OnIsLockedChanging(value)
            Me.ReportPropertyChanging("IsLocked")
            Me._IsLocked = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("IsLocked")
            Me.OnIsLockedChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _IsLocked As Global.System.Nullable(Of Boolean)
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnIsLockedChanging(ByVal value As Global.System.Nullable(Of Boolean))
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnIsLockedChanged()
        End Sub
    '''<summary>
    '''架构中不存在属性 IsAdmin 的任何注释。
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property IsAdmin() As Global.System.Nullable(Of Boolean)
        Get
            Return Me._IsAdmin
        End Get
        Set
            Me.OnIsAdminChanging(value)
            Me.ReportPropertyChanging("IsAdmin")
            Me._IsAdmin = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("IsAdmin")
            Me.OnIsAdminChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _IsAdmin As Global.System.Nullable(Of Boolean)
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnIsAdminChanging(ByVal value As Global.System.Nullable(Of Boolean))
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnIsAdminChanged()
        End Sub
    '''<summary>
    '''架构中不存在属性 Role 的任何注释。
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property Role() As String
        Get
            Return Me._Role
        End Get
        Set
            Me.OnRoleChanging(value)
            Me.ReportPropertyChanging("Role")
            Me._Role = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
            Me.ReportPropertyChanged("Role")
            Me.OnRoleChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _Role As String
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnRoleChanging(ByVal value As String)
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnRoleChanged()
        End Sub
End Class
'''<summary>
'''架构中不存在 DBModel.AppUsage 的注释。
'''</summary>
'''<KeyProperties>
'''UsageID
'''</KeyProperties>
<Global.System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName:="DBModel", Name:="AppUsage"),  _
 Global.System.Runtime.Serialization.DataContractAttribute(IsReference:=true),  _
 Global.System.Serializable()>  _
Partial Public Class AppUsage
    Inherits Global.System.Data.Objects.DataClasses.EntityObject
    '''<summary>
    '''创建新的 AppUsage 对象。
    '''</summary>
    '''<param name="usageID">UsageID 的初始值。</param>
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Shared Function CreateAppUsage(ByVal usageID As Long) As AppUsage
        Dim appUsage As AppUsage = New AppUsage()
        appUsage.UsageID = usageID
        Return appUsage
    End Function
    '''<summary>
    '''架构中不存在属性 UsageID 的任何注释。
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property UsageID() As Long
        Get
            Return Me._UsageID
        End Get
        Set
            Me.OnUsageIDChanging(value)
            Me.ReportPropertyChanging("UsageID")
            Me._UsageID = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("UsageID")
            Me.OnUsageIDChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _UsageID As Long
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnUsageIDChanging(ByVal value As Long)
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnUsageIDChanged()
        End Sub
    '''<summary>
    '''架构中不存在属性 AppName 的任何注释。
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property AppName() As String
        Get
            Return Me._AppName
        End Get
        Set
            Me.OnAppNameChanging(value)
            Me.ReportPropertyChanging("AppName")
            Me._AppName = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
            Me.ReportPropertyChanged("AppName")
            Me.OnAppNameChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _AppName As String
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnAppNameChanging(ByVal value As String)
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnAppNameChanged()
        End Sub
    '''<summary>
    '''架构中不存在属性 VisitTime 的任何注释。
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property VisitTime() As Global.System.Nullable(Of Date)
        Get
            Return Me._VisitTime
        End Get
        Set
            Me.OnVisitTimeChanging(value)
            Me.ReportPropertyChanging("VisitTime")
            Me._VisitTime = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("VisitTime")
            Me.OnVisitTimeChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _VisitTime As Global.System.Nullable(Of Date)
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnVisitTimeChanging(ByVal value As Global.System.Nullable(Of Date))
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnVisitTimeChanged()
        End Sub
    '''<summary>
    '''架构中不存在属性 UserIP 的任何注释。
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property UserIP() As String
        Get
            Return Me._UserIP
        End Get
        Set
            Me.OnUserIPChanging(value)
            Me.ReportPropertyChanging("UserIP")
            Me._UserIP = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
            Me.ReportPropertyChanged("UserIP")
            Me.OnUserIPChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _UserIP As String
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnUserIPChanging(ByVal value As String)
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnUserIPChanged()
        End Sub
    '''<summary>
    '''架构中不存在属性 UserID 的任何注释。
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property UserID() As Global.System.Nullable(Of Long)
        Get
            Return Me._UserID
        End Get
        Set
            Me.OnUserIDChanging(value)
            Me.ReportPropertyChanging("UserID")
            Me._UserID = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("UserID")
            Me.OnUserIDChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _UserID As Global.System.Nullable(Of Long)
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnUserIDChanging(ByVal value As Global.System.Nullable(Of Long))
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnUserIDChanged()
        End Sub
End Class
